services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: timesheetdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5450:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
